
name: douban
on: 
  schedule:
  - cron: "30 * * * *"

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: movie
      uses: xia0bs/doumark-action@master
      with:
        id: lizheming
        type: movie
        format: notion
        dir: 5b9ea15365024ff4a51f7109179dce60
        notion_token: ${{ secrets.NOTION_TOKEN }}
