
name: douban
on: 
  schedule:
  - cron: "30 * * * *"

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: movie
      uses: xia0bs/doumark-action@master
      with:
        id: "151651419"
        type: movie
        format: notion
        dir: 3b72531862e9482d9d846f229fee03dd
        notion_token: ${{ secrets.notion_token }}
