
name: douban
on: 
  schedule:
  - cron: "30 * * * *"

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: movie
      uses: xia0bs/doumark-action@master
      with:
        id: "151651419"
        type: movie
        format: notion
        dir: "2e09329dac56499d841cc28da5dd81b0"
        notion_token: ${{ secrets.notion_token }}
